# Generated by Django 4.2.23 on 2025-07-28 12:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.CharField(max_length=20)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('position_size', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='trade_screenshots/')),
                ('notes', models.TextField(blank=True)),
                ('emotion', models.CharField(blank=True, choices=[('CALM', 'Calm'), ('ANXIOUS', 'Anxious'), ('GREEDY', 'Greedy'), ('FEARFUL', 'Fearful'), ('CONFIDENT', 'Confident'), ('EXCITED', 'Excited'), ('FRUSTRATED', 'Frustrated'), ('DISCIPLINED', 'Disciplined')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
