# Generated by Django 4.2.23 on 2025-08-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-open_date']},
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='date_time',
            new_name='open_date',
        ),
        migrations.AddField(
            model_name='trade',
            name='close_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='swap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset',
            field=models.CharField(choices=[('GBPUSD', 'GBP/USD'), ('EURUSD', 'EUR/USD'), ('USDJPY', 'USD/JPY'), ('USDCHF', 'USD/CHF'), ('AUDUSD', 'AUD/USD'), ('USDCAD', 'USD/CAD'), ('NZDUSD', 'NZD/USD'), ('EURGBP', 'EUR/GBP'), ('EURJPY', 'EUR/JPY'), ('GBPJPY', 'GBP/JPY'), ('XAUUSD', 'XAU/USD (Gold)'), ('XAGUSD', 'XAG/USD (Silver)'), ('BTCUSD', 'BTC/USD'), ('ETHUSD', 'ETH/USD')], max_length=20),
        ),
    ]
