# Generated by Django 4.2.23 on 2025-08-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_alter_trade_options_rename_date_time_trade_open_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='is_merged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trade',
            name='merged_group_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='merged_trades_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='trade',
            name='original_trades_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
