# Generated by Django 4.2.23 on 2025-08-07 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0004_trade_is_merged_trade_merged_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='asset',
            field=models.CharField(choices=[('EURUSD', 'EUR/USD'), ('GBPUSD', 'GBP/USD'), ('USDJPY', 'USD/JPY'), ('USDCHF', 'USD/CHF'), ('AUDUSD', 'AUD/USD'), ('USDCAD', 'USD/CAD'), ('NZDUSD', 'NZD/USD'), ('EURGBP', 'EUR/GBP'), ('EURJPY', 'EUR/JPY'), ('GBPJPY', 'GBP/JPY'), ('XAUUSD', 'XAU/USD (Gold)'), ('XAGUSD', 'XAG/USD (Silver)'), ('BTCUSD', 'BTC/USD'), ('ETHUSD', 'ETH/USD')], max_length=20),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('ECONOMIC', 'Economic Event'), ('EARNINGS', 'Earnings Report'), ('NEWS', 'Market News'), ('PERSONAL', 'Personal Event'), ('WEBINAR', 'Webinar/Education'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('event_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('achievement_type', models.CharField(choices=[('MILESTONE', 'Trading Milestone'), ('PROFIT', 'Profit Target'), ('STREAK', 'Winning Streak'), ('EDUCATION', 'Education/Certification'), ('PERSONAL', 'Personal Goal'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('achieved_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-achieved_date'],
            },
        ),
    ]
